### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by doakey3**
This is a rewrite of DashTable. It performs the same function as before, but with fewer errors.

### CODE REVIEW

**Comment by gustavklopp** [comment]
Hi @doakey3 ! Thanks for your interest for this project!
I've got serious health problem and I've reduced a lot all my code activities. 
It would be good if this project doesn't die... Would you like to be the principal maintainer of this project?

**Comment by doakey3** [comment]
I'm so sorry you're having health troubles. If you'd like to transfer the project to me, I will continue to make updates and improvements.

**Comment by gustavklopp** [comment]
To transfer ownership, you need to change the name of "doakey3/dashTable" (or remove that) apparently: I've got an error: "doakey3/dashTable already exists"

**Comment by doakey3** [comment]
I have deleted my branch of DashTable. Maybe it will work now? I've never made a pip project before. Do I need any password or anything to upload new versions of DashTable PyPI?

**Comment by gustavklopp** [comment]
You need to create an account on https://pypi.python.org/pypi
Give me your username there and I will transfer to you the ownership on PyPI

**Comment by doakey3** [comment]
I have accepted the transfer. My username on PyPI is doakey3

**Comment by gustavklopp** [comment]
Okat, that's done! Hope you have fun with that!

**Pull request closed without merging**
